# Generated by Django 2.2.24 on 2021-11-28 16:39

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0003_default_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 11, 30, 16, 39, 59, 748307, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
