# Generated by Django 2.2.24 on 2021-12-19 23:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0009_auto_20211216_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 23, 2, 33, 653316, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
