# Generated by Django 2.2.24 on 2021-12-19 23:41

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('authnapp', '0010_auto_20211219_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2021, 12, 21, 23, 41, 53, 108727, tzinfo=utc), verbose_name='актуальность ключа'),
        ),
    ]
